module.exports = {
	BinOpAdd: require('./BinOpAdd.js'),
	BinOpBitwiseAnd: require('./BinOpBitwiseAnd.js'),
	BinOpBitwiseOr: require('./BinOpBitwiseOr.js'),
	BinOpBitwiseXor: require('./BinOpBitwiseXor.js'),
	BinOpCmpEQ: require('./BinOpCmpEQ.js'),
	BinOpCmpGE: require('./BinOpCmpGE.js'),
	BinOpCmpGT: require('./BinOpCmpGT.js'),
	BinOpCmpLE: require('./BinOpCmpLE.js'),
	BinOpCmpLT: require('./BinOpCmpLT.js'),
	BinOpCmpNEQ: require('./BinOpCmpNEQ.js'),
	BinOpDiv: require('./BinOpDiv.js'),
	BinOpIntDiv: require('./BinOpIntDiv.js'),
	BinOpLogicalAnd: require('./BinOpLogicalAnd.js'),
	BinOpLogicalOr: require('./BinOpLogicalOr.js'),
	BinOpMod: require('./BinOpMod.js'),
	BinOpMul: require('./BinOpMul.js'),
	BinOpPow: require('./BinOpPow.js'),
	BinOpShiftLeft: require('./BinOpShiftLeft.js'),
	BinOpShiftRight: require('./BinOpShiftRight.js'),
	BinOpSub: require('./BinOpSub.js')
}